Tencent/tdesign-vue-starter

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> chore(issue template): add issue template

package-lock.json, package.json, src/layouts/components/Header.vue, src/layouts/components/Search.vue, src/layouts/index.tsx, src/layouts/setting.vue, src/style/layout.less, vite.config.js
- Upgrade to `tdesign-vue@0.32.0-alpha.1`
- Adaptating BEM style changes
=> feat: upgrade tdesign-vue & fix BEM

src/pages/login/index.less
=> fix(login): fix bg img position

src/router/modules/others.ts
修复页面配置如下时，点击页面顶部菜单项【登录页】无法正确跳转至登录页的问题
=> fix: fix incorrect router component

src/App.vue, src/layouts/setting.vue, src/store/modules/setting.ts
=> fix: copy custom theme and mode

src/pages/form/base/index.vue
fix form base page validate error
=> fix(form/base): optimize form/base form validate

src/layouts/components/MenuContent.tsx
=> feat(router): add router hidden

src/style/layout.less
- https://github.com/Tencent/tdesign-vue-starter/issues/75
同步 https://github.com/Tencent/tdesign-vue-next-starter/pull/71 改动
=> fix: sidenav z-index

package-lock.json, package.json
=> chore: upgrade tdesign-vue to 0.35.1

src/layouts/components/MenuContent.tsx
- 新特性提交，支持菜单配置跳转外链
```
{
path: 'https://tdesign.tencent.com',
meta: { title: '友情链接' },
},
```
- feat: 支持菜单配置跳转外链
=> feat: 支持配置跳转外链

src/style/layout.less
- fix: #54 
- fix: 修复混合布局下列表页滚动问题
=> fix(mix-layout): add min-width to t-content

package.json
=> chore: upgrade tdesign-vue to 0.38.x

src/layouts/index.tsx, src/store/modules/tab-router.ts, src/style/layout.less
- 演示代码改进
- https://github.com/Tencent/tdesign-vue-next-starter/issues/105
- https://github.com/Tencent/tdesign-vue-next-starter/issues/102
- feat: 多标签Tab页功能增加持久化逻辑
- feat: 优化多标签Tab页逻辑
=> feat: optimize tab router

package.json
=> chore: upgrade dependencies map

src/store/modules/user.ts
=> update mock roles

src/pages/list/base/index.vue, src/pages/list/components/CommonTable.vue
- 演示代码改进 增加Table组件吸顶
- fix(table): 增加Table组件吸顶
=> feat(table): 增加吸顶展示

src/store/modules/setting.ts
- 日常 bug 修复 `showFooter`开关无效问题
- fix: 修复 showFooter开关无效问题
=> fix: showFooter switch

src/layouts/index.tsx, src/store/modules/tab-router.ts
=> feat: add ignore cache routes demo

src/service/service-user.ts
=> chore: fix incorrect content

package.json
=> chore: hot fix vue2 version

package.json
- fix: 升级`vite-plugin-vue2-svg` 解决vue2.7发布导致的依赖关系问题
=> chore: upgrade svg plugin version

.vscode/settings.json, package.json, src/layouts/components/LayoutContent.vue, src/layouts/components/LayoutHeader.vue, src/layouts/components/LayoutSidebar.vue, src/pages/dashboard/detail/index.vue, src/style/reset.less
- feat: 升级组件库至0.45.2
- chore: 优化组件引入命名
=> feat: upgrade tdesign version

package.json, src/pages/form/base/index.vue, src/pages/form/step/index.vue, src/pages/list/filter/index.vue, src/pages/list/tree/index.vue
- feat: 升级组件库至0.46版本
- feat: 统一示例代码用卡片组件
=> feat: upgrade tdesign-vue to 0.46

src/layouts/components/LayoutContent.vue
=> fix: tab router close tabs ahead

src/layouts/components/LayoutContent.vue
=> feat(tab-router): enable action for inactive tab

package.json
- feat: 升级组件库依赖至0.49+ 下拉菜单样式有改动
=> chore: upgrade tdesign to 0.49.0

src/components/product-card/index.vue
=> fix: product card method name mistakes

package.json, src/layouts/components/Header.vue, src/layouts/components/Notice.vue, src/layouts/setting.vue, src/pages/dashboard/base/index.vue, src/pages/dashboard/detail/index.vue
=> chore: upgrade tdesign-vue to 0.50

README-zh_CN.md, README.md, package.json
=> chore: release 0.4.4

package.json, src/components/result/index.vue, src/components/thumbnail/index.vue, src/config/color.ts, src/layouts/components/Notice.vue, src/layouts/setting.vue, src/pages/detail/base/index.less, src/pages/detail/secondary/index.less, src/pages/list/base/index.vue, src/pages/list/components/CommonTable.vue, src/pages/list/tree/index.vue, src/pages/login/components/components-header.vue, src/pages/login/index.less, src/pages/result/fail/index.vue, src/pages/result/network-error/index.vue, src/pages/result/success/index.vue, src/pages/user/index.less, src/style/layout.less, src/style/reset.less, src/style/theme/default.less, src/style/variables.less
- refactor: 废弃大量内置`less variables`, 尺寸、色彩、字体、圆角及阴影统一使用组件库内置变量 具体变量可参考 https://tdesign.tencent.com/starter/docs/vue-next/design-token  
- refactor: 升级默认主题色的配色方案  组件库升级至0.50.1请参照改动
=> refactor: remove deprecated less variables

src/layouts/components/MenuContent.vue
=> fix: 3rd level menu path

package.json
=> chore: fix submenu padding

package.json, src/layouts/components/SideNav.vue, src/pages/login/index.less, src/style/layout.less
- https://github.com/Tencent/tdesign-vue-starter/issues/204
- fix: 修复布局尺寸改动导致的样式问题
=> fix: fix layout size calculation

package.json, src/layouts/components/SideNav.vue, src/pages/form/base/index.less, src/pages/login/index.less, src/style/layout.less
=> feat: upgrde tdesign to 1.0

.env.site, package.json
=> chore: fix site deploy

.env.site, package.json, src/config/host.ts
=> fix: fix site deploy

src/router/index.js
=> chore: history router

globals.d.ts, src/router/index.js
=> chore: fix page path

src/style/layout.less
https://github.com/Tencent/tdesign-common/pull/1094
- 修复 logo 高度计算错误的问题
=> fix: box size

package.json
=> chore: release 0.5.1

.env, .env.development, .env.site
=> chore: fix default deploy base url

package.json
=> chore: release 0.6.1

package.json, src/layouts/components/Content.vue, src/pages/dashboard/base/index.vue, src/store/modules/tab-router.ts
- feat: 新增 `keepAlive` meta 方便配置是否开启页面缓存
- feat: 组件库升级至 1.3.0 新增部分组件示例
=> feat: add kee-alive meta config

package.json
=> chore: release 0.6.2

.github/workflows/pull-request.yml
- chore: add site branch workflow 
=> chore: add site build workflow

package.json
https://github.com/okonet/lint-staged#v10
- chore: lint-staged v10以后不需要git add
=> chore: lint-staged remove git add

src/layouts/setting/page-config.vue
=> fix: fix drawer style

package.json
=> fix: add lodash to dependencies

src/layouts/components/MenuContent.vue
https://github.com/Tencent/tdesign-vue-starter/issues/88
对于配置了一级路由、没有设置 redirect 的导航栏项目，在 `:value` 中添加回退的 `item.path`。效果如下：
- fix(layouts-header): 为配置了一级路由、没有设置 redirect 的导航栏项目添加选中效果
=> fix(layouts-header): 为配置了一级路由、没有设置 redirect 的导航栏项目添加选中效果

package.json, src/pages/detail/advanced/index.less, src/pages/detail/advanced/index.vue, src/pages/detail/base/index.less, src/pages/detail/base/index.vue
-  #304
- feat: 升级`tdesign-vue`至 `1.9.0`
- refactor: 详情页页基本信息替换为`Descriptions`组件
=> refactor(detail): 升级tdesign-vue版本，detail页基本信息替换为descriptions组件

.gitignore, package-lock.json, src/constants/index.ts, src/pages/list/base/index.vue, src/pages/list/components/CommonTable.vue
背景：原本没有保留某种lock的本意是让用户自行选择，但是实际执行下来发现有许多用户因为lock文件没有保留，导致出现本地和线上不一致的问题，所以恢复其中一种lock文件
- feat: 调整默认lock文件配置
=> chore: remove npm lock file ignore
